name: Licensed

on:
  push: {branches: main}
  pull_request: {branches: main}

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Check licenses
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - run: npm ci
      - run: npm run licensed-check
